// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY';
export const ADJUST_ITEM_ATTRIBUTE = 'ADJUST_ITEM_ATTRIBUTE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
